### ISSUE TITLE
Conflicting name with Eris PM

### ISSUE THREAD

**Issue by nmushegian** [ethpm/epm-spec#1]
Possibly an issue? It's a shame because I like the name "epm" a lot, but if Eris got it first seems fair to avoid it. On the other hand, maybe they'd be willing to work together?

https://github.com/eris-ltd/eris-pm

**Comment by tcoulter** [comment]
@nmushegian good call. What name do you suggest? Or are you only implying we change `epm` to `ethpm`?

**Comment by nmushegian** [comment]
I think the best case is cooperation with eris and using `epm`. I think `ethpm` is actually worse, because to me it is more like `evmpm`; Ethereum is a specific network name, but in my mind packages can target different environments. I believe Eris's pm is also good at handling many chains.

TBH I also think it's fine to just keep using epm and find a new name once there's more attention from the conflict

**Comment by tcoulter** [comment]
> TBH I also think it's fine to just keep using epm and find a new name once there's more attention from the conflict

Agreed. 

> I think the best case is cooperation with eris and using epm.

What does cooperation look like? Happy to in general, but we need to make sure their stuff solves all the issues we're trying to solve. When you say "cooperation", are you inferring that this project perhaps shouldn't exist?

**Comment by nmushegian** [comment]
I was thinking this is a merger of all pm ideas happening right now, so more like they would realize outsourcing their package manager system to people who are willing to subsidize it anyway would be smart. Of course this requires outlining everyone's different needs and wants in any case.
