### ISSUE TITLE
JSON-schema for ABI

### ISSUE THREAD

**Issue by pipermerriam** [ethpm/epm-spec#20]
The ABI portion of the json-schema isn't currently fleshed out.

Here is an existing schema for that data structure.

https://github.com/pipermerriam/ethereum-function-signature-registry/blob/master/func_sig_registry/utils/abi.py

**Comment by VoR0220** [comment]
The ABI already comes in a json schema...just wrap that into your contract instance object.

**Comment by mhhf** [comment]
@pipermerriam why do you think we need to validate the abi here? It did change once during solidity/ ethereum development and there is a change it will change again. So validating an already standardized output (assuming no manipulation is done), would only produce the overhead of keeping up with the validation. Also it changes across solidity versions, so abi validation would depend on the version.
I'd propose to just keeping it a blackbox.
