### ISSUE TITLE
Beginning to wonder why manifest reference is necessary 

### ISSUE THREAD

**Issue by VoR0220** [ethpm/epm-spec#21]
https://github.com/ethpm/epm-spec/blob/master/release-lock-file-s.md#package_manifest-string-required

I'm beginning to think this isn't necessary and thus should not be a requirement of the spec. Does anyone take umbridge with this?

**Comment by pipermerriam** [comment]
The reason I included it is that it provides a frozen version of all of the *meta* information that is included in that document.  Older releases may have been released under a different license than the project is currently using and this information would be lost if it isn't somehow referenced from the release.  Not the strongest use case but it's what comes to mind immediately.

**Comment by VoR0220** [comment]
I would then propose that we take out the "must include" clause.

**Comment by pipermerriam** [comment]
I think I'm fine with this change. Would like to hear what others think.
Will you create a pull request for this?

**Comment by VoR0220** [comment]
si

**Comment by pipermerriam** [comment]
#23 implements this.
