### ISSUE TITLE
The Lock File Manifesto

### ISSUE THREAD

**Issue by pipermerriam** [ethpm/epm-spec#22]
Going to try and distill some things from a few places and conversations and bring this all together.

There are currently two files that we have specifications for.  They are:

* **Package Manifest**: https://github.com/ethpm/epm-spec/blob/master/package-manifest-s.md
* **Release Lock File**: https://github.com/ethpm/epm-spec/blob/master/release-lock-file-s.md

I propose that we make the following adjustments.

1. Rename **Release Lock File** to **Release File** or `<insert your better name here>`.
2. Add a new third specified file which we can refer to as **Package Manager Lock File** or **PM Lock File** or just **Lock File** if you're [into the whole brevity thing](https://www.youtube.com/watch?v=Be7Og9Gc_KY)

**Comment by tcoulter** [comment]
I won't be saving a package manager lock file, as I don't see a necessary
requirement for it at this time. I think the naming scheme is fine given
that there's only ever one type of lock file I interact with (for now).

Until we can have two versions of `owned` in the same Solidity project I
don't see a need for a package lock file.

**Comment by tcoulter** [comment]
That should say "I think the current naming scheme is fine". I'm not having
confusions about it, but if others are then we can change it.

**Comment by VoR0220** [comment]
I dont think the distinction is necessary. For packages one lock file for release is fine.

**Comment by pipermerriam** [comment]
@tcoulter Now that I've given this a bit more thought, I *think* I see your point in not actually needing a package manager lockfile.  Closing until something indicates otherwise.
