### ISSUE TITLE
Alternative build & package manager ideas

### ISSUE THREAD

**Issue by raineorshine** [ethpm/epm-spec#3]
I wanted to post a reference to this in-depth discussion by the PureScript community of developing a new package manager. Be warned, the discussion's been active since 2014, so it's a lot, but I think it could offer some useful insight. The PureScript community in general as an extension of the Haskell community is a very bright group of folks.

https://github.com/purescript/purescript/issues/631

We should learn from the mistakes of other package managers. Many of them are pointed out here.

(TLDR; they seem to have [coalesced around bower](https://github.com/purescript/purescript/issues/631#issuecomment-237775069), interestingly enough. Good discussion of npm's advantages and disadvantages, as well as other package managers.

**Comment by mhhf** [comment]
https://github.com/mhhf/spore lol
